name: hn_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  ## Replace flutter SDK dependency with flutter_web
  #flutter:
  #  sdk: flutter
  flutter_web: any

  cupertino_icons: ^0.1.2
  url_launcher: 5.2.5
  built_value: 6.8.2
  http: ^0.12.0+2

dev_dependencies:
  ## Similarly replace test libraries to web test libraries
  #flutter_test:
  #  sdk: flutter
  flutter_web_test: any

  test_api: 0.2.5
  test: 1.6.3
  built_value_generator: 6.8.2
  ## Add these dependencies to enable the Dart web build system
  build_runner: 1.4.0
  build_web_compilers: any

flutter:
  uses-material-design: true

## Assets are handled differenly in web. So remove them from here
# flutter:
#   uses-material-design: true
#   assets:
#     - asset/
#
#   fonts:
#   - family: Plaster
#     fonts:
#     - asset: asset/fonts/plaster/Plaster-Regular.ttf

## Add the following:
## flutter_web packages are not published to pub.dartlang.org
## These overrides tell the package tools to get them from GitHub
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test