name: hn_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: 5.2.5
  built_value: 6.8.2
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  test_api: 0.2.5
  test: 1.6.3
  build_runner: 1.4.0
  built_value_generator: 6.8.2

flutter:

  uses-material-design: true
